# TCL File Generated by Component Editor 17.0
# Thu Sep 28 17:58:08 EDT 2017
# DO NOT MODIFY


#
# one_shot "One-Shot Timer" v1.0
# David Rauth 2017.09.28.17:58:08
# One-Shot Timer
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module one_shot
#
set_module_property DESCRIPTION "One-Shot Timer"
set_module_property NAME one_shot
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "David Rauth"
set_module_property DISPLAY_NAME "One-Shot Timer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL one_shot
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file one_shot.v VERILOG PATH design/one_shot.v TOP_LEVEL_FILE


#
# parameters
#
add_parameter WIDTH INTEGER 32 "Set this to limit the number of outputs to reduce logic utilization."
set_parameter_property WIDTH DEFAULT_VALUE 32
set_parameter_property WIDTH DISPLAY_NAME "Number of outputs"
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES 1:32
set_parameter_property WIDTH DESCRIPTION "Set this to limit the number of outputs to reduce logic utilization."
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter MAX_PULSE INTEGER 32 "Set this to limit the size of the timers to reduce logic utilization."
set_parameter_property MAX_PULSE DEFAULT_VALUE 32
set_parameter_property MAX_PULSE DISPLAY_NAME "Number of timer bits"
set_parameter_property MAX_PULSE TYPE INTEGER
set_parameter_property MAX_PULSE UNITS None
set_parameter_property MAX_PULSE ALLOWED_RANGES 1:32
set_parameter_property MAX_PULSE DESCRIPTION "Set this to limit the size of the timers to reduce logic utilization."
set_parameter_property MAX_PULSE HDL_PARAMETER true
add_parameter INVERT_DEFAULT STD_LOGIC_VECTOR 0 ""
set_parameter_property INVERT_DEFAULT DEFAULT_VALUE 0
set_parameter_property INVERT_DEFAULT DISPLAY_NAME "Polarity register default"
set_parameter_property INVERT_DEFAULT WIDTH WIDTH
set_parameter_property INVERT_DEFAULT TYPE STD_LOGIC_VECTOR
set_parameter_property INVERT_DEFAULT UNITS None
set_parameter_property INVERT_DEFAULT ALLOWED_RANGES 0:4294967295
set_parameter_property INVERT_DEFAULT DESCRIPTION ""
set_parameter_property INVERT_DEFAULT HDL_PARAMETER true
add_parameter ENABLE_DEFAULT STD_LOGIC_VECTOR 0 ""
set_parameter_property ENABLE_DEFAULT DEFAULT_VALUE 0
set_parameter_property ENABLE_DEFAULT DISPLAY_NAME "Enable register default"
set_parameter_property ENABLE_DEFAULT WIDTH WIDTH
set_parameter_property ENABLE_DEFAULT TYPE STD_LOGIC_VECTOR
set_parameter_property ENABLE_DEFAULT UNITS None
set_parameter_property ENABLE_DEFAULT ALLOWED_RANGES 0:4294967295
set_parameter_property ENABLE_DEFAULT DESCRIPTION ""
set_parameter_property ENABLE_DEFAULT HDL_PARAMETER true
add_parameter TIME_DEFAULT STD_LOGIC_VECTOR 10000 ""
set_parameter_property TIME_DEFAULT DEFAULT_VALUE 10000
set_parameter_property TIME_DEFAULT DISPLAY_NAME "Timer register default"
set_parameter_property TIME_DEFAULT WIDTH MAX_PULSE
set_parameter_property TIME_DEFAULT TYPE STD_LOGIC_VECTOR
set_parameter_property TIME_DEFAULT UNITS None
set_parameter_property TIME_DEFAULT ALLOWED_RANGES 0:4294967295
set_parameter_property TIME_DEFAULT DESCRIPTION ""
set_parameter_property TIME_DEFAULT HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point avalon_slave_0
#
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 1
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 s_address address Input 2
add_interface_port avalon_slave_0 s_read read Input 1
add_interface_port avalon_slave_0 s_readdata readdata Output 32
add_interface_port avalon_slave_0 s_write write Input 1
add_interface_port avalon_slave_0 s_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


#
# connection point conduit_end
#
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end pulse_out export Output WIDTH


set_module_property VALIDATION_CALLBACK validate_me

proc validate_me {} {
    set numout [get_parameter_value WIDTH]
    set poldefault [get_parameter_value INVERT_DEFAULT]
    set endefault [get_parameter_value ENABLE_DEFAULT]
    set timerval [get_parameter_value TIME_DEFAULT]
    set timerbits [get_parameter_value MAX_PULSE]

    if {$timerval >= (1 << $timerbits)} {
        send_message ERROR "Not enough timer bits to hold timer register default value."
    }

    if {$poldefault >= (1 << $numout)} {
        send_message ERROR "Not enough outputs for polarity register default value."
    }

    if {$endefault >= (1 << $numout)} {
        send_message ERROR "Not enough outputs for enable register default value."
    }
}
