# TCL File Generated by Component Editor 14.0
# Thu Dec 24 12:37:33 EST 2015
# DO NOT MODIFY


# 
# vme_intf "vme_bridge" v1.0
# R. Carickhoff 2015.12.24.12:37:33
# Interface to standard VME backplane
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module vme_intf
# 
set_module_property DESCRIPTION "Interface to standard VME backplane"
set_module_property NAME vme_intf
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My_Components
set_module_property AUTHOR "R. Carickhoff"
set_module_property DISPLAY_NAME vme_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vme_intf
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vme_intf.v VERILOG PATH ./design/vme_intf.v TOP_LEVEL_FILE
add_fileset_file dtack_timer.v VERILOG PATH ./design/dtack_timer.v
add_fileset_file interrupt_control.v VERILOG PATH ./design/interrupt_control.v
add_fileset_file interrupt_handler.v VERILOG PATH ./design/interrupt_handler.v


# 
# parameters
# 
add_parameter BIG_ENDIAN INTEGER 1
set_parameter_property BIG_ENDIAN DEFAULT_VALUE 1
set_parameter_property BIG_ENDIAN DISPLAY_NAME BIG_ENDIAN
set_parameter_property BIG_ENDIAN TYPE INTEGER
set_parameter_property BIG_ENDIAN UNITS None
set_parameter_property BIG_ENDIAN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BIG_ENDIAN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 125000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 s_write_0 write Input 1
add_interface_port avalon_slave_0 s_read_0 read Input 1
add_interface_port avalon_slave_0 s_address_0 address Input 25
add_interface_port avalon_slave_0 s_writedata_0 writedata Input 16
add_interface_port avalon_slave_0 s_byteenable_0 byteenable Input 2
add_interface_port avalon_slave_0 s_readdata_0 readdata Output 16
add_interface_port avalon_slave_0 s_waitrequest_0 waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_slave_1
# 
add_interface avalon_slave_1 avalon end
set_interface_property avalon_slave_1 addressUnits WORDS
set_interface_property avalon_slave_1 associatedClock clock
set_interface_property avalon_slave_1 associatedReset reset
set_interface_property avalon_slave_1 bitsPerSymbol 8
set_interface_property avalon_slave_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_1 burstcountUnits WORDS
set_interface_property avalon_slave_1 explicitAddressSpan 0
set_interface_property avalon_slave_1 holdTime 0
set_interface_property avalon_slave_1 linewrapBursts false
set_interface_property avalon_slave_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_1 readLatency 0
set_interface_property avalon_slave_1 readWaitTime 1
set_interface_property avalon_slave_1 setupTime 0
set_interface_property avalon_slave_1 timingUnits Cycles
set_interface_property avalon_slave_1 writeWaitTime 0
set_interface_property avalon_slave_1 ENABLED true
set_interface_property avalon_slave_1 EXPORT_OF ""
set_interface_property avalon_slave_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_1 s_writedata_1 writedata Input 32
add_interface_port avalon_slave_1 s_write_1 write Input 1
add_interface_port avalon_slave_1 s_waitrequest_1 waitrequest Output 1
add_interface_port avalon_slave_1 s_readdata_1 readdata Output 32
add_interface_port avalon_slave_1 s_read_1 read Input 1
add_interface_port avalon_slave_1 s_byteenable_1 byteenable Input 4
add_interface_port avalon_slave_1 s_address_1 address Input 30
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender s_irq_0 irq Output 1


# 
# connection point vme_intf
# 
add_interface vme_intf conduit end
set_interface_property vme_intf associatedClock clock
set_interface_property vme_intf associatedReset reset
set_interface_property vme_intf ENABLED true
set_interface_property vme_intf EXPORT_OF ""
set_interface_property vme_intf PORT_NAME_MAP ""
set_interface_property vme_intf CMSIS_SVD_VARIABLES ""
set_interface_property vme_intf SVD_ADDRESS_GROUP ""

add_interface_port vme_intf vme_sysfail_n vme_sysfail_n Input 1
add_interface_port vme_intf vme_irq_n vme_irq_n Input 7
add_interface_port vme_intf vme_iackout_n vme_iackout_n Output 1
add_interface_port vme_intf vme_iack_n vme_iack_n Output 1
add_interface_port vme_intf vme_dtack_n vme_dtack_n Input 1
add_interface_port vme_intf vme_ds1_n vmd_ds1_n Output 1
add_interface_port vme_intf vme_ds0_n vme_ds0_n Output 1
add_interface_port vme_intf vme_write_n vme_write_n Output 1
add_interface_port vme_intf vme_sysrst_n vme_sysrst_n Output 1
add_interface_port vme_intf vme_lword_n vme_lword_n Output 1
add_interface_port vme_intf vme_as_n vme_as_n Output 1
add_interface_port vme_intf vme_am vme_am Output 6
add_interface_port vme_intf vme_db vme_db Bidir 32
add_interface_port vme_intf vme_a vme_a Output 31

