# TCL File Generated by Component Editor 14.0
# Thu Jan 14 16:30:20 EST 2016
# DO NOT MODIFY


# 
# 16550_uart "16500_uart" v1.0
# R. Carickhoff 2016.01.14.16:30:20
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module 16550_uart
# 
set_module_property DESCRIPTION ""
set_module_property NAME 16550_uart
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My_Components
set_module_property AUTHOR "R. Carickhoff"
set_module_property DISPLAY_NAME 16500_uart
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_uart_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_uart_top.v VERILOG PATH avalon_uart_top.v TOP_LEVEL_FILE
add_fileset_file raminfr.v VERILOG PATH raminfr.v
add_fileset_file timescale.v VERILOG PATH timescale.v
add_fileset_file uart_debug_if.v VERILOG PATH uart_debug_if.v
add_fileset_file uart_defines.v VERILOG PATH uart_defines.v
add_fileset_file uart_receiver.v VERILOG PATH uart_receiver.v
add_fileset_file uart_regs.v VERILOG PATH uart_regs.v
add_fileset_file uart_rfifo.v VERILOG PATH uart_rfifo.v
add_fileset_file uart_sync_flops.v VERILOG PATH uart_sync_flops.v
add_fileset_file uart_tfifo.v VERILOG PATH uart_tfifo.v
add_fileset_file uart_top.v VERILOG PATH uart_top.v
add_fileset_file uart_transmitter.v VERILOG PATH uart_transmitter.v
add_fileset_file uart_wb.v VERILOG PATH uart_wb.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 s_address address Input 3
add_interface_port avalon_slave_0 s_writedata writedata Input 8
add_interface_port avalon_slave_0 s_write write Input 1
add_interface_port avalon_slave_0 s_read read Input 1
add_interface_port avalon_slave_0 s_chipselect chipselect Input 1
add_interface_port avalon_slave_0 s_waitrequest_n waitrequest_n Output 1
add_interface_port avalon_slave_0 s_readdata readdata Output 8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end srx_pad_i uart_sin Input 1
add_interface_port conduit_end stx_pad_o uart_sout Output 1
add_interface_port conduit_end rts_pad_o uart_rts Output 1
add_interface_port conduit_end cts_pad_i uart_cts Input 1
add_interface_port conduit_end dtr_pad_o uart_dtr Output 1
add_interface_port conduit_end dsr_pad_i uart_dsr Input 1
add_interface_port conduit_end ri_pad_i uart_ri Input 1
add_interface_port conduit_end dcd_pad_i uart_dcd Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point interrupt_sender_1
# 
add_interface interrupt_sender_1 interrupt end
set_interface_property interrupt_sender_1 associatedAddressablePoint ""
set_interface_property interrupt_sender_1 associatedClock clock
set_interface_property interrupt_sender_1 associatedReset reset
set_interface_property interrupt_sender_1 bridgedReceiverOffset ""
set_interface_property interrupt_sender_1 bridgesToReceiver ""
set_interface_property interrupt_sender_1 ENABLED true
set_interface_property interrupt_sender_1 EXPORT_OF ""
set_interface_property interrupt_sender_1 PORT_NAME_MAP ""
set_interface_property interrupt_sender_1 CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender_1 SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender_1 s_irq irq Output 1

